url: "https://wrenzenzen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lindsay's dev space" # the name of your site, e.g. ACME Corp.
#pagination: 5
#paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
collections:
  - projects
